"""remove active_spawns group fk

Revision ID: ec64244b1b3b
Revises: 27696e1acac3
Create Date: 2026-04-19 09:05:48.572008+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec64244b1b3b'
down_revision: Union[str, None] = '27696e1acac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_active_spawns_chat_id_groups'), 'active_spawns', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_active_spawns_chat_id_groups'), 'active_spawns', 'groups', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
