"""add last_activity_at to trades

Revision ID: c9e84ba34068
Revises: a3c8f21db45e
Create Date: 2026-04-19 02:49:53.732237+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9e84ba34068"
down_revision: Union[str, None] = "a3c8f21db45e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trades",
        sa.Column("last_activity_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "last_activity_at")
    # ### end Alembic commands ###
