"""add incense and xp_boost columns

Revision ID: 27696e1acac3
Revises: 023385890446
Create Date: 2026-04-19 08:59:12.365445+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27696e1acac3'
down_revision: Union[str, None] = '023385890446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('incense_until', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('incense_activated_by', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('incense_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('xp_boost_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp_boost_until')
    op.drop_column('users', 'incense_until')
    op.drop_column('groups', 'incense_activated_by')
    op.drop_column('groups', 'incense_until')
    # ### end Alembic commands ###
