"""Incense spawn refactor

Revision ID: 1061fdf64fb1
Revises: ec64244b1b3b
Create Date: 2026-04-19 09:31:15.963020+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1061fdf64fb1'
down_revision: Union[str, None] = 'ec64244b1b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('incense_spawns_remaining', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('groups', 'incense_until')
    op.add_column('users', sa.Column('incense_spawns_remaining', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'incense_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('incense_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'incense_spawns_remaining')
    op.add_column('groups', sa.Column('incense_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('groups', 'incense_spawns_remaining')
    # ### end Alembic commands ###
